services:
  db:
    image: 'postgis/postgis:18-3.6'
    user: ${POSTGRES_USER:-postgres}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DATABASE: ${POSTGRES_USER:-postgres}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env

volumes:
  postgres:
